# Generated by Django 6.0.7 on 2026-08-07 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_teacherassignment'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_date', models.DateField()),
                ('session_number', models.PositiveIntegerField()),
                ('lesson_summary', models.TextField()),
                ('present_count', models.PositiveIntegerField()),
                ('absent_count', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=30)),
                ('review_comment', models.TextField(blank=True)),
                ('is_late', models.BooleanField(default=False)),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_reports', to='academic.teacherassignment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
