# Generated by Django 6.0.7 on 2026-08-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessionreport',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teachertermrate',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
