# Generated by Django 6.0.7 on 2026-08-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_salary_is_deleted_sessionreport_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='sessionreport',
            name='is_deleted',
        ),
    ]
