# Generated by Django 6.0.7 on 2026-08-18 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_session'),
        ('finance', '0005_remove_salary_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionreport',
            name='session_date',
        ),
        migrations.RemoveField(
            model_name='sessionreport',
            name='session_number',
        ),
        migrations.AddField(
            model_name='sessionreport',
            name='session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='academic.session'),
        ),
    ]
