# Generated by Django 6.0.7 on 2026-08-18 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_session'),
        ('finance', '0006_remove_sessionreport_session_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionreport',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='academic.session'),
        ),
        migrations.AlterField(
            model_name='sessionreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
    ]
