# Generated by Django 6.0.7 on 2026-08-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_sessionreport_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionreport',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
