# Generated by Django 6.0.7 on 2026-08-20 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_sessionreport_rejected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionreport',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
