# Generated by Django 6.0.7 on 2026-08-24 19:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_session_session_date'),
        ('finance', '0009_sessionreport_resubmitted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.UniqueConstraint(fields=('teacher', 'year', 'month'), name='unique_teacher_salary_per_month'),
        ),
    ]
