# Generated by Django 6.0.7 on 2026-08-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_salary_year_salary_unique_teacher_salary_per_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salary",
            name="year",
            field=models.PositiveSmallIntegerField(),
        ),
    ]