# Generated by Django 6.0.7 on 2026-08-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
