# Generated by Django 6.0.7 on 2026-08-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_teacherassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='term',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
