# Generated by Django 6.0.7 on 2026-08-12 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_class_is_deleted_teacherassignment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='session_duration',
            field=models.PositiveIntegerField(choices=[(60, '60 minutes'), (90, '90 minutes'), (120, '120 minutes')]),
        ),
    ]
