# Generated by Django 6.0.7 on 2026-08-18 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_class_session_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('session_number', models.PositiveIntegerField()),
                ('session_date', models.DateField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academic.class')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('classroom', 'session_number'), name='unique_session_number_per_class'), models.UniqueConstraint(fields=('classroom', 'session_date'), name='unique_session_date_per_class')],
            },
        ),
    ]
