# Generated by Django 6.0.7 on 2026-08-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_date',
            field=models.DateTimeField(),
        ),
    ]
